version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.5
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: ts-jest
    versions:
    - 26.5.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.2.3
